### ISSUE TITLE
Researcher Profile not created smoothly

### ISSUE THREAD

**Issue by spcags** [4Science/DSpace#17]
Both DSpace-cris 5.8.0 and 6.x 

(1) logged as admin 
click CRIS Module => Organization Units => Add Organization Unit 

filled the form and “Save Changes”. 
It did not complete the submission due to required field “Director”
although the field was filled. 

Warning: Field required

 CRIS Module => Projects => Add Projects 

the same as in [1], required field “Project Coordinator” was not filled.

(2) Access Control =>  Authorization => Manage a Community's Policies => Edit Policies
Internal System Error
The system has experienced an internal error. Please try to do what you were doing again, and if the problem persists, please contact us so we can fix the problem.
 
There is a workaround, ie, if "Research Output" was selected, it worked ok. So this is more a UX 
issue. When only one item exists, default should focus on the item, then it should work. Need to add the selection UX.

**Comment by abollini** [comment]
Thanks to share your experience with DSpace-CRIS.
To allow easier tracking of the issues I recommend to open separate issue for any individual problem, question or functionality.

(1) it is a UX problem. The system works as expected, tested on the demos sites. The director field is a pointer to a researcher page, this mean that you cannot input free text, instead you need to pick one of the suggestion made by the autocomplete (try to type Bol)

(2) it is a problem commons to the base DSpace so I recommend eventually to open an issue in the JIRA system http://jira.duraspace.org

As both problems are UX issue limited to the administrators that can be solved with minimal training considering that the UX will be completely reviewed in DSpace(-CRIS) 7 I'm going to close this issue as **won't fix**

If you decide to invest some time fixing the issue please consider to provide it back, in particular the (2) could be no too complex to fix and can be shared with the whole dspace community
