### ISSUE TITLE
Documentation Improvement: explain the Solr cores required by DSpace CRIS

### ISSUE THREAD

**Issue by saschaszott** [4Science/DSpace#356]
The current DS CRIS 2023.01 documentation does not contain a description of the Solr cores that are required by DSpace CRIS.

Which Solr cores are required by DSpace CRIS? DSpace 7 has 4 Solr cores (marked red in the screenshot below). 

![image](https://github.com/4Science/DSpace/assets/952735/94556222-91ca-459b-af51-19fbe304dd85)

DSpace CRIS provides configuration files for **5 additional Solr cores** in https://github.com/4Science/DSpace/tree/dspace-cris-7/dspace/solr. 

The file `docker-compose.yml` does not consider these additional Solr cores. We found out that in DSpace CRIS 2023.01.00 at least dedup is additionally required. 

Could you please explain the purpose of the additional Solr cores in the DS CRIS documentation.

**Comment by corrad82-4s** [comment]
`suggestion` core is related to the suggestions created by the Notification Broker feature, e.g. the Publication Claim which scans the openaire graph looking for potential matches of a researcher (https://4science.github.io/oaire-eld/) . 
Other additional cores brief descriptions will be added in next release's documentation.

**Comment by saschaszott** [comment]
> `suggestion` core is related to the suggestions created by the Notification Broker feature, e.g. the Publication Claim which scans the openaire graph looking for potential matches of a researcher (https://4science.github.io/oaire-eld/) . Other additional cores brief descriptions will be added in next release's documentation.

Thank you, @corrad82-4s !
