### ISSUE TITLE
command subscription-send does not support option -t / --Type

### ISSUE THREAD

**Issue by saschaszott** [4Science/DSpace#366]
## Bug Description

In DSpace CRIS 2022.03 the option `-t / --Type` was supported in the `subscription-send` command. The DS CRIS 2023.01 documentation still describes this parameter at page 78.

> -t or --Type representing notification type to be sent, one between "content" and "statistics"

The option was removed in the code base in December 2022.

Currently (in DS CRIS 2023.01), the command execution throws an exception if option `-t` is used:

```sh
$ ./dspace subscription-send -f D -t content
org.apache.commons.cli.UnrecognizedOptionException: Unrecognized option: -t
```

**Comment by corrad82-4s** [comment]
Hello, this issue has been solved with commit https://github.com/4Science/DSpace/commit/191ac97dbc2fa4e1dc15e5f17887c3334d450757
