### ISSUE TITLE
Blank screen after install

### ISSUE THREAD

**Issue by Phu2** [4Science/DSpace#71]
I'm trying to install dspace-5_x_x-cris using

* Ubuntu 18.04
* PostgreSQL 10.6
* openjdk version 1.8.0_191
* Tomcat 8.5.30

and the JSP User Interface. After an `ant fresh_install` it only shows a blank screen. The dspace.log says

> 2019-04-08 15:14:35,765 ERROR org.dspace.storage.rdbms.DatabaseRegistryUpdater @ Error attempting to add/update default DSpace Groups

When running 

`[dspace]/bin/dspace database info`

the State column shows "Success" for all migrations.

[dspace.log.2019-04-08.txt](https://github.com/4Science/DSpace/files/3055142/dspace.log.2019-04-08.txt)

**Comment by Phu2** [comment]
With the exact same installation steps (via Ansible) - but with sources from https://github.com/DSpace/DSpace/tree/dspace-5_x - i got a properly running DSpace instance.

**Comment by lap82** [comment]
Thank you @Phu2 we take in charge the issue. We have no notice of this problem in our experience, but from your log file seems that there are two concurrent database migration. It's a strange case. I'm investigating.

**Comment by lap82** [comment]
Dear @Phu2, 

I setup from scratch the dspace-5_x_x-cris successfully in most of use cases. I can reproduce a similar issue combining some different factors. In particular I try to start two Tomcat one with "jspui/solr" and the other with "oai" at same time (or nearly). Can you try to add to the Ansible procedure the database migration before starts servlet container? To setup the database from the bin folder run the follow instruction:
`./dspace database migrate`

Let me know.

**Comment by Phu2** [comment]
Thank you very much for your investigations, @lap82 ! Unfortunately i am currently out of office and without access to the servers. So i will try it out and come back to you on monday.

**Comment by Phu2** [comment]
With the additional database migration step the initial error is gone. Now the database table `epersongroup` consists of two group ids `0` and `1` in . So this seems to be a necessary fix for what might have been gone wrong when initializing the database. 

But i'm still looking at a blank screen. Not sure if this caused by misconfiguration by myself or some something else. There are some 

> Failed to startup the DSpace Service Manager

messages in the catalina.out log. I need to investigate these errors further and grateful for any hints.

[catalina.out.txt](https://github.com/4Science/DSpace/files/3080794/catalina.out.txt)

**Comment by lap82** [comment]
Dear @Phu2 

from the log file I see:

```
15-Apr-2019 13:18:54.684 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server version:        Apache Tomcat/8.5.30 (Ubuntu)
15-Apr-2019 13:18:54.684 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server built:          Aug 13 2018 20:23:56 UTC
15-Apr-2019 13:18:54.685 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server number:         8.5.30.0
15-Apr-2019 13:18:54.685 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log OS Name:               Linux
15-Apr-2019 13:18:54.685 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log OS Version:            4.15.18-11-pve
15-Apr-2019 13:18:54.685 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Architecture:          amd64
15-Apr-2019 13:18:54.685 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Java Home:             /usr/lib/jvm/java-11-openjdk-amd64
15-Apr-2019 13:18:54.685 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log JVM Version:           10.0.2+13-Ubuntu-1ubuntu0.18.04.4
15-Apr-2019 13:18:54.686 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log JVM Vendor:            Oracle Corporation
15-Apr-2019 13:18:54.686 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log CATALINA_BASE:         /srv/tomcat8_dspace
15-Apr-2019 13:18:54.686 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log CATALINA_HOME:         /usr/share/tomcat8
```
can you downgrade Java version from the version 11 to the version 8? by the way, due to a security patches released on newest tomcat minor version https://tomcat.apache.org/security-8.html, I suggest to upgrade tomcat to the last 8.5.40 version

**Comment by Phu2** [comment]
Oh, dear! It's the Java version. It has been installed and set as default during installation of other software components. After setting Java 8 as default the installation runs smoothly. No need of the additional database migration step. Grazie mille, @lap82 !
