### ISSUE TITLE
Dspace create administrator failed

### ISSUE THREAD

**Issue by abbaskhalil** [4Science/DSpace#8]
dspace create-administrator failed with this mesage : 

> exception in thread "main" java.lang.outofmemoryerror: gc overhead limit exceeded

**Comment by lap82** [comment]
Try to tune the Java Heap Space follow the documentation https://wiki.duraspace.org/display/DSDOC5x/Performance+Tuning+DSpace#PerformanceTuningDSpace-GivetheCommandLineToolsMoreMemory

If after tuning the Java parameters you have again this issue maybe you have a dirty installation folder. Check the log file please.
