### ISSUE TITLE
Unable to submit an item using upload file

### ISSUE THREAD

**Issue by marc-brouard** [4Science/DSpace#84]
When using the New Submission, Upload a file the details from the file are not extracted. I have tried this with a ris file and a bibtex file. No errors are logged. But looking at the code

In `SubmissionLookupJSONRequest.java` when doing the BTE transformation, it creates a new `TransformationSpec`, but this creation fails with a null pointer error. Line 293. The exact error is 

```
Method threw 'java.lang.NullPointerException' exception. Cannot evaluate gr.ekt.bte.core.TransformationSpec.toString()
```
The TransformationSpec is defined in bte-core-0.9.3.5-sources.jar

I don't think that this is the whole reason why the upload is failing though, it looks like the TransformationSpec may need setting up.

**Comment by rfazio** [comment]
I think I resolved with this commit:
7e4959078447c8558f75c34a8561825aa872e5b5

Thank you very much

**Comment by marc-brouard** [comment]
Thank you, yes that works now. Greatly appreciated.
