### ISSUE TITLE
ClassNotFoundException - DSpaceRestApplication

### ISSUE THREAD

**Issue by debashis1982** [4Science/DSpace#9]
Hi,

According to this commit -https://github.com/4Science/DSpace/commit/a0f88cd94ea146a9a5ee1c4bf6939e9495d655c3
class org.dspace.rest.DSpaceRestApplication has been removed but it is still referenced in the web.xml of dspace-rest project
https://github.com/4Science/DSpace/blob/dspace-5_x_x-cris/dspace-rest/src/main/webapp/WEB-INF/web.xml
which is why the project dspace-rest while being loaded into tomcat container is error-ing out with ClassNotFoundException - DSpaceRestApplication

Is that class not required anymore? Can we get rid of it from the web.xml?

Thanks,
Debashis

**Comment by lap82** [comment]
Ok thank you. I will fix it shortly.
