### ISSUE TITLE
Browse Withdrawn items show unrelated content

### ISSUE THREAD

**Issue by abollini** [4Science/DSpace#98]
The `${dspace.url}/dspace-admin/withdrawn` shows unrelated content (orgunit browsing, other report projects) instead than the expected browse of withdrawn items

**Comment by francescopioscognamiglio** [comment]
Issue resolved with following commits:
- DSpace-CRIS 5: https://github.com/4Science/DSpace/commit/0c3b10440fe2b98703b49db2e08350e963755da9
- DSpace-CRIS 6: https://github.com/4Science/DSpace/commit/ae733b8acc99ce62fc19825ebf13563336c5022f
